# Site settings
author: Krystian Dennis
title: The Art of Data Science
header-img: img/home-bg.png
email: krystiandennis@gmail.com
copyright_name: Krystian Dennis
description: > # this means to ignore newlines until "baseurl:"
  Had to come up with something on the spot! 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  krystiandennis

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
